services:
  webui:
    image: smmtracker-webui
    container_name: webui
    restart: unless-stopped
    build:
      context: .
      dockerfile: SMMTracker.WebUI/Dockerfile
    ports:
      - "80:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/SMMTracker.db
    volumes:
      - ./data:/app/data
    networks:
      - smm-net

  tgbot:
    image: smmtracker-tgbot
    container_name: tgbot
    restart: unless-stopped
    build:
      context: .
      dockerfile: SMMTracker.TgBot/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/SMMTracker.db
    volumes:
      - ./data:/app/data
    networks:
      - smm-net

networks:
  smm-net:
    driver: bridge