services:
  webui:
    image: smmtracker-webui
    build:
      context: .
      dockerfile: SMMTracker.WebUI/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  tgbot:
    image: smmtracker-tgbot
    build:
      context: .
      dockerfile: SMMTracker.TgBot/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development